const works = [{
        "id": "1",
        "title": "春树秋香图",
        "author": "唐伯虎",
        "link": "detail.html",
        "imgSrc": "images/zp1.jpg"
    }, {
        "id": "2",
        "title": "春树秋香图",
        "author": "唐伯虎",
        "link": "detail.html",
        "imgSrc": "images/zp2.jpg"
    }, {
        "id": "3",
        "title": "春树秋香图",
        "author": "唐伯虎",
        "link": "detail.html",
        "imgSrc": "images/zp3.jpg"
    }, {
        "id": "4",
        "title": "春树秋香图",
        "author": "唐伯虎",
        "link": "detail.html",
        "imgSrc": "images/zp4.jpg"
    }, {
        "id": "1",
        "title": "春树秋香图",
        "author": "唐伯虎",
        "link": "detail.html",
        "imgSrc": "images/zp2.jpg"
    }, {
        "id": "2",
        "title": "春树秋香图",
        "author": "唐伯虎",
        "link": "detail.html",
        "imgSrc": "images/zp2.jpg"
    }, {
        "id": "3",
        "title": "春树秋香图",
        "author": "唐伯虎",
        "link": "detail.html",
        "imgSrc": "images/zp2.jpg"
    }, {
        "id": "4",
        "title": "春树秋香图",
        "author": "唐伯虎",
        "link": "detail.html",
        "imgSrc": "images/zp2.jpg"
    }, {
        "id": "1",
        "title": "春树秋香图",
        "author": "唐伯虎",
        "link": "detail.html",
        "imgSrc": "images/zp3.jpg"
    }, {
        "id": "2",
        "title": "春树秋香图",
        "author": "唐伯虎",
        "link": "detail.html",
        "imgSrc": "images/zp3.jpg"
    }, {
        "id": "3",
        "title": "春树秋香图",
        "author": "唐伯虎",
        "link": "detail.html",
        "imgSrc": "images/zp3.jpg"
    }, {
        "id": "4",
        "title": "春树秋香图",
        "author": "唐伯虎",
        "link": "detail.html",
        "imgSrc": "images/zp4.jpg"
    }, {
        "id": "3",
        "title": "春树秋香图",
        "author": "唐伯虎",
        "link": "detail.html",
        "imgSrc": "images/zp3.jpg"
    }, {
        "id": "4",
        "title": "春树秋香图",
        "author": "唐伯虎",
        "link": "detail.html",
        "imgSrc": "images/zp4.jpg"
    }];